export type Role = "student" | "teacher" | "guardian" | "admin";
export type Row = Record<string, unknown>;
export type MemberRow = Row & { id: string; email: string; displayName: string; status: string; roles: string };
export type GuardianLinkRow = Row & { guardianUserId: string; studentUserId: string; status: string };
export type SecretStatus = { configured: boolean; suffix: string };
export type PublicPlatformSettings = {
  jwtTtlSeconds: number;
  aiModel: string;
  aiKey: SecretStatus;
  openAiKey: SecretStatus;
  speechKey: SecretStatus;
  moderationKey: SecretStatus;
};
export type QualityMetricDetail = { id: string; label: string; meta?: string };
export type QualityMetric = {
  label: string;
  value: number;
  numerator: number;
  denominator: number;
  unit: "percent" | "count";
  note: string;
  details: QualityMetricDetail[];
  trendAvailable: boolean;
};
export type QualityMetrics = Record<string, QualityMetric>;
export type WorkspaceData = {
  workspace: { tenantId: string; name: string; region: string; sampleData: boolean };
  user: { id: string; email: string; displayName: string; roles: Role[]; mustChangePassword?: boolean };
  classes: Row[]; assignments: Row[]; submissions: Row[]; submissionReviews: Row[]; mastery: Row[]; documents: Row[];
  lessonPlans: Row[]; notifications: Row[]; consents: Row[]; audits: Row[]; invitations: Row[]; members: MemberRow[]; guardianLinks: GuardianLinkRow[];
  learningObjectives: Row[]; diagnosticItems: Row[]; diagnosticSummary: Row | null; recommendations: Row[]; learningPlan: Row[];
  availableStudents: Array<{ id: string; displayName: string }>; selectedStudent: { id: string; displayName: string } | null;
  weeklyReport: { submittedCount: number; reviewedCount: number; averageScore: number | null; masteryAverage: number; pendingRecommendations: number };
  masteryMatrix: Row[]; qualityMetrics: QualityMetrics | null; enrollments: Row[];
  services: Record<string, { status: string; label: string }>;
  platformSettings?: PublicPlatformSettings;
  generatedAt: string;
};
export type Notify = (title: string, detail: string, tone?: "success" | "error") => void;
export type Act = (action: string, payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
export const stringValue = (value: unknown, fallback = "—") => typeof value === "string" && value ? value : fallback;
export const numberValue = (value: unknown, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
